<?php
require __DIR__ . '/_admin.php';
require_login();

$id = (int)($_GET['id'] ?? $_POST['id'] ?? 0);
$db = db();
$st = $db->prepare('SELECT * FROM firearms WHERE id = ?');
$st->execute([$id]);
$model = $id ? ($st->fetch() ?: null) : null;
if ($id && !$model) {
    flash('That model no longer exists.', 'err');
    redirect(url('admin/models.php'));
}

const PLACEHOLDER_NOTE = 'Caliber is a placeholder: this model was made in several calibers; set the real one. ';

// [column, label, type, hint]. Metric columns are generated by the database, so only imperial is entered.
$groups = [
    'Basics' => [
        ['manufacturer', 'Manufacturer', 'text', ''],
        ['model', 'Model', 'text', ''],
        ['category', 'Type', 'category', ''],
        ['caliber', 'Caliber', 'text', 'e.g. 9mm Luger, .357 Magnum / .38 Special, 12 gauge'],
        ['action', 'Action', 'text', 'e.g. Semi-auto, striker; Revolver, DA/SA; Pump action'],
        ['capacity', 'Capacity (rounds)', 'num', 'Factory capacity. Over 10 automatically shows "(10 round limit in CA)".'],
        ['capacity_note', 'Capacity note', 'text', ''],
    ],
    'California' => [
        ['ca_rostered', 'CA handgun roster', 'roster', 'Check oag.ca.gov/firearms/certified-handguns'],
        ['ca_roster_checked_on', 'Roster checked on', 'date', 'Filled with today when you change the roster status.'],
    ],
    'Dimensions (inches)' => [
        ['barrel_length_in', 'Barrel length', 'num', ''],
        ['overall_length_in', 'Overall length', 'num', ''],
        ['height_in', 'Height', 'num', ''],
        ['width_in', 'Width', 'num', ''],
        ['sight_radius_in', 'Sight radius', 'num', ''],
        ['length_of_pull_in', 'Length of pull', 'num', 'Long guns'],
    ],
    'Weight (ounces)' => [
        ['weight_oz', 'Weight, unloaded', 'num', '16 oz = 1 lb'],
        ['weight_empty_mag_oz', 'With empty magazine', 'num', ''],
        ['weight_loaded_oz', 'Loaded', 'num', ''],
    ],
    'Barrel & trigger' => [
        ['barrel_material', 'Barrel material', 'text', ''],
        ['barrel_twist', 'Barrel twist', 'text', 'e.g. 1:16" RH'],
        ['thread_pattern', 'Thread pattern', 'text', 'e.g. 1/2"-28'],
        ['chamber_length_in', 'Chamber length (in)', 'num', 'Shotguns'],
        ['choke', 'Choke', 'text', 'Shotguns'],
        ['trigger_pull_lb', 'Trigger pull (lb)', 'num', 'Single action / striker'],
        ['trigger_pull_da_lb', 'Double-action pull (lb)', 'num', 'DA/SA guns'],
    ],
    'Build' => [
        ['frame_material', 'Frame', 'text', ''],
        ['finish', 'Finish', 'text', ''],
        ['stock_grip', 'Stock / grip', 'text', ''],
        ['sights', 'Sights', 'text', ''],
    ],
    'Retail' => [
        ['msrp_usd', 'MSRP ($)', 'num', ''],
        ['release_year', 'Release year', 'num', ''],
        ['sku', 'SKU', 'text', ''],
        ['upc', 'UPC', 'text', ''],
    ],
    'Text & sources' => [
        ['description', 'Description (shown on every listing of this model)', 'textarea', ''],
        ['product_url', 'Manufacturer page', 'text', ''],
        ['source_url', 'Spec source URL', 'text', 'Where the specs came from.'],
        ['data_notes', 'Data notes (private)', 'textarea', 'Conflicts between sources, things to verify.'],
        ['slug', 'URL name (slug)', 'text', 'Leave empty to create one from make + model.'],
    ],
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_post_csrf();
    $data = [];
    foreach ($groups as $fields) {
        foreach ($fields as [$col, , $type]) {
            if ($type === 'num') {
                $data[$col] = in_num($col);
            } elseif ($type === 'roster') {
                $data[$col] = in_bool($col);
            } elseif ($type === 'category') {
                $data[$col] = in_array($_POST[$col] ?? '', CATEGORIES, true) ? $_POST[$col] : 'handgun';
            } else {
                $data[$col] = in_text($col, 10000);
            }
        }
    }
    foreach (['capacity', 'release_year'] as $c) {
        $data[$c] = $data[$c] === null ? null : (int)$data[$c];
    }
    if ($data['category'] !== 'handgun') {
        $data['ca_rostered'] = null;
    }
    if ($data['ca_rostered'] !== ($model['ca_rostered'] ?? null) && $data['ca_rostered'] !== null && ($data['ca_roster_checked_on'] ?? '') === ($model['ca_roster_checked_on'] ?? '')) {
        $data['ca_roster_checked_on'] = date('Y-m-d');
    }
    if (isset($_POST['caliber_confirmed']) && $data['data_notes'] !== null) {
        $data['data_notes'] = trim(str_replace(trim(PLACEHOLDER_NOTE), '', $data['data_notes'])) ?: null;
    }
    if (!$data['slug']) {
        $data['slug'] = trim(preg_replace('/[^a-z0-9]+/', '-', strtolower($data['manufacturer'] . ' ' . $data['model'])), '-');
    }
    try {
        if (!$data['manufacturer'] || !$data['model']) {
            throw new RuntimeException('Manufacturer and model are required.');
        }
        if ($id) {
            $set = implode(', ', array_map(fn($k) => "$k = :$k", array_keys($data)));
            $db->prepare("UPDATE firearms SET $set, updated_at = datetime('now') WHERE id = :id")->execute($data + ['id' => $id]);
            flash('Model saved.');
        } else {
            $cols = implode(', ', array_keys($data));
            $db->prepare("INSERT INTO firearms ($cols) VALUES (:" . implode(', :', array_keys($data)) . ')')->execute($data);
            $id = (int)$db->lastInsertId();
            flash('Model created.');
        }
        redirect(url('admin/model.php', ['id' => $id]));
    } catch (Throwable $e) {
        flash(friendly_db_error($e), 'err');
        $model = array_merge($model ?? [], $data);
    }
}

$v = $model ?? ['category' => 'handgun'];
$placeholder = strpos((string)($v['data_notes'] ?? ''), trim(PLACEHOLDER_NOTE)) !== false;
$heading = $model ? $v['manufacturer'] . ' ' . $v['model'] : 'New model';
$listings = [];
if ($id) {
    $ls = $db->prepare('SELECT id, stock_number, status FROM listings WHERE firearm_id = ? ORDER BY id');
    $ls->execute([$id]);
    $listings = $ls->fetchAll();
}

admin_header($heading, 'models');
?>
<div class="crumbs"><a href="<?= e(url('admin/models.php')) ?>">Models</a> / <?= e($heading) ?></div>
<div class="admin-head"><h1 class="page-title"><?= e($heading) ?></h1></div>
<?php if ($model): ?>
  <p class="muted">Changes here apply to every listing of this model (<?= count($listings) ?>).
    <a href="<?= e(url('admin/listing.php', ['firearm_id' => $id])) ?>">Add a listing for this model</a></p>
<?php endif; ?>

<form method="post" action="<?= e(url('admin/model.php', ['id' => $id ?: null])) ?>" class="admin-form">
  <?= csrf_field() ?>
  <?php foreach ($groups as $legend => $fields): ?>
    <fieldset>
      <legend><?= e($legend) ?></legend>
      <div class="grid-2">
      <?php foreach ($fields as [$col, $label, $type, $hint]):
          $value = $v[$col] ?? null;
          $wide = in_array($type, ['textarea'], true) || in_array($col, ['description', 'product_url', 'source_url', 'data_notes'], true); ?>
        <div class="field<?= $wide ? ' span-2' : '' ?>">
          <label for="<?= $col ?>"><?= e($label) ?></label>
          <?php if ($type === 'textarea'): ?>
            <textarea class="input" id="<?= $col ?>" name="<?= $col ?>" rows="<?= $col === 'description' ? 5 : 3 ?>"><?= e($value ?? '') ?></textarea>
          <?php elseif ($type === 'category'): ?>
            <select class="select" id="<?= $col ?>" name="<?= $col ?>"><?php foreach (CATEGORIES as $c) echo opt($c, type_label($c) . ($c === 'other' ? ' (receivers, kits)' : ''), $value); ?></select>
          <?php elseif ($type === 'roster'): ?>
            <select class="select" id="<?= $col ?>" name="<?= $col ?>">
              <?= opt('', 'Not checked / not a handgun', $value ?? '') ?><?= opt('1', 'On the roster', $value ?? '') ?><?= opt('0', 'Not on the roster', $value ?? '') ?>
            </select>
          <?php else: ?>
            <input class="input<?= $type === 'num' ? ' mono' : '' ?>" id="<?= $col ?>" name="<?= $col ?>" type="<?= $type === 'date' ? 'date' : 'text' ?>"<?= $type === 'num' ? ' inputmode="decimal"' : '' ?> value="<?= e($type === 'num' && $value !== null ? num($value, 4) : ($value ?? '')) ?>">
          <?php endif; ?>
          <?php if ($hint): ?><span class="hint"><?= e($hint) ?></span><?php endif; ?>
          <?php if ($col === 'caliber' && $placeholder): ?>
            <label class="check"><input type="checkbox" name="caliber_confirmed" value="1"> Caliber is now correct (clears the "placeholder" note)</label>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
      </div>
    </fieldset>
  <?php endforeach; ?>
  <div class="save-bar"><button class="btn btn-accent" type="submit"><?= $model ? 'Save model' : 'Create model' ?></button>
    <a class="link-btn" href="<?= e(url('admin/models.php')) ?>">Cancel</a></div>
</form>
<?php admin_footer();
