<?php
require __DIR__ . '/_admin.php';
require_login();

$id = (int)($_GET['id'] ?? $_POST['id'] ?? 0);
$db = db();
$st = $db->prepare('SELECT * FROM firearms WHERE id = ?');
$st->execute([$id]);
$model = $id ? ($st->fetch() ?: null) : null;
if ($id && !$model) {
    flash('That firearm no longer exists.', 'err');
    redirect(url('admin/models.php'));
}

const PLACEHOLDER_NOTE = 'Caliber is a placeholder: this model was made in several calibers; set the real one. ';

// Arrived from a listing's "Add a new firearm": go back to that listing after saving.
$returnListing = (($_GET['return'] ?? $_POST['return'] ?? '') === 'listing');
$returnId = (int)($_GET['listing'] ?? $_POST['listing'] ?? 0);
$backToListing = fn(int $fid) => url('admin/listing.php', ['id' => $returnId ?: null, 'firearm_id' => $fid]);
$norm = fn($s) => preg_replace('/[^a-z0-9]/', '', strtolower((string)$s));

// [column, label, type, hint]. Metric columns are generated by the database, so only imperial is entered.
$groups = [
    'Basics' => [
        ['manufacturer', 'Manufacturer', 'text', ''],
        ['model', 'Model', 'text', ''],
        ['category', 'Type', 'category', ''],
        ['caliber', 'Caliber', 'choice', 'Pick from the list. Use "Add a new one" only if it really isn\'t there.'],
        ['action', 'Action', 'choice', 'Pick from the list. Use "Add a new one" only if it really isn\'t there.'],
        ['capacity', 'Capacity (rounds)', 'num', 'Factory capacity. Over 10 automatically shows "(10 round limit in CA)".'],
        ['capacity_note', 'Capacity note', 'text', ''],
    ],
    'California' => [
        ['ca_rostered', 'CA handgun roster', 'roster', 'Check oag.ca.gov/firearms/certified-handguns'],
        ['ca_roster_checked_on', 'Roster checked on', 'date', 'Filled with today when you change the roster status.'],
        ['ca_roster_entry', 'Roster entry', 'text', 'Set when you pick this firearm on the CA roster page, e.g. /firearms/handgun/grp.'],
    ],
    'Dimensions (inches)' => [
        ['barrel_length_in', 'Barrel length', 'num', ''],
        ['overall_length_in', 'Overall length', 'num', ''],
        ['height_in', 'Height', 'num', ''],
        ['width_in', 'Width', 'num', ''],
        ['sight_radius_in', 'Sight radius', 'num', ''],
        ['length_of_pull_in', 'Length of pull', 'num', 'Long guns'],
    ],
    'Weight (ounces)' => [
        ['weight_oz', 'Weight, unloaded', 'num', '16 oz = 1 lb'],
        ['weight_empty_mag_oz', 'With empty magazine', 'num', ''],
        ['weight_loaded_oz', 'Loaded', 'num', ''],
    ],
    'Barrel & trigger' => [
        ['barrel_material', 'Barrel material', 'text', ''],
        ['barrel_twist', 'Barrel twist', 'text', 'e.g. 1:16" RH'],
        ['thread_pattern', 'Thread pattern', 'text', 'e.g. 1/2"-28'],
        ['chamber_length_in', 'Chamber length (in)', 'num', 'Shotguns'],
        ['choke', 'Choke', 'text', 'Shotguns'],
        ['trigger_pull_lb', 'Trigger pull (lb)', 'num', 'Single action / striker'],
        ['trigger_pull_da_lb', 'Double-action pull (lb)', 'num', 'DA/SA guns'],
    ],
    'Build' => [
        ['frame_material', 'Frame', 'text', ''],
        ['finish', 'Finish', 'text', ''],
        ['stock_grip', 'Stock / grip', 'text', ''],
        ['sights', 'Sights', 'text', ''],
    ],
    'Retail' => [
        ['msrp_usd', 'MSRP ($)', 'num', ''],
        ['release_year', 'Release year', 'num', ''],
        ['sku', 'SKU', 'text', ''],
        ['upc', 'UPC', 'text', ''],
    ],
    'Text & sources' => [
        ['description', 'Description (shown on every listing of this model)', 'textarea', ''],
        ['product_url', 'Manufacturer page', 'text', ''],
        ['source_url', 'Spec source URL', 'text', 'Where the specs came from.'],
        ['data_notes', 'Data notes (private)', 'textarea', 'Conflicts between sources, things to verify.'],
        ['slug', 'URL name (slug)', 'text', 'Leave empty to create one from make + model.'],
    ],
];

// ----- Stock photo (shown on NEW listings of this firearm that have no photos of their own) -----
// "Find" downloads the product photo from the manufacturer page and shows it for checking;
// nothing is saved until "Use this photo".
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['stock_action']) && $model) {
    require_post_csrf();
    $slug = (string)$model['slug'];
    $preview = $_SESSION['stock_preview'][$id] ?? null;
    $clearPreview = function () use ($id, $preview) {
        if ($preview && is_file($preview['file'])) {
            @unlink($preview['file']);
        }
        unset($_SESSION['stock_preview'][$id]);
    };
    try {
        switch ((string)$_POST['stock_action']) {
            case 'upload':
                $file = $_FILES['stock_file'] ?? [];
                if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK || !is_uploaded_file($file['tmp_name']) || filesize($file['tmp_name']) > PHOTO_MAX_BYTES) {
                    throw new RuntimeException('The photo was not received, or it is too large.');
                }
                stock_save((string)file_get_contents($file['tmp_name']), $slug);
                $clearPreview();
                flash('Stock photo saved.');
                break;
            case 'find':
                $page = trim((string)($_POST['stock_page'] ?? ''));
                if (!preg_match('~^https?://~i', $page)) {
                    throw new RuntimeException('Enter the manufacturer page address (starting with https://).');
                }
                [$img, $bytes] = stock_fetch_from_page($page, $model['image_url'] ?? null);
                $clearPreview();
                $tmp = tempnam(sys_get_temp_dir(), 'stock');
                file_put_contents($tmp, $bytes);
                $_SESSION['stock_preview'][$id] = ['file' => $tmp, 'image' => $img, 'page' => $page];
                flash('Found a photo on the manufacturer page. Check it below, then choose "Use this photo".');
                break;
            case 'use':
                if (!$preview || !is_file($preview['file'])) {
                    throw new RuntimeException('That preview has expired. Find the photo again.');
                }
                stock_save((string)file_get_contents($preview['file']), $slug);
                $clearPreview();
                flash('Stock photo saved.');
                break;
            case 'discard':
                $clearPreview();
                break;
            case 'remove':
                stock_delete($slug);
                flash('Stock photo removed.');
                break;
        }
    } catch (RuntimeException $e) {
        flash($e->getMessage(), 'err');
    }
    redirect(url('admin/model.php', ['id' => $id]) . '#stock-photo');
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    require_post_csrf();
    $data = [];
    foreach ($groups as $fields) {
        foreach ($fields as [$col, , $type]) {
            if ($type === 'num') {
                $data[$col] = in_num($col);
            } elseif ($type === 'roster') {
                $data[$col] = in_bool($col);
            } elseif ($type === 'category') {
                $data[$col] = in_array($_POST[$col] ?? '', CATEGORIES, true) ? $_POST[$col] : 'handgun';
            } elseif ($type === 'choice') {
                // Dropdown of values already used, or "Add a new one" (typed into <col>__new).
                $data[$col] = ($_POST[$col] ?? '') === '__new' ? in_text($col . '__new', 10000) : in_text($col, 10000);
            } else {
                $data[$col] = in_text($col, 10000);
            }
        }
    }
    foreach (['capacity', 'release_year'] as $c) {
        $data[$c] = $data[$c] === null ? null : (int)$data[$c];
    }
    // One spelling per caliber / action (known aliases become the usual spelling).
    $data['caliber'] = canonical_value('caliber', $data['caliber']);
    $data['action'] = canonical_value('action', $data['action']);
    if ($data['category'] !== 'handgun') {
        $data['ca_rostered'] = null;
    }
    if ($data['ca_rostered'] !== 1) {
        $data['ca_roster_entry'] = null;   // a roster link only makes sense for on-roster firearms
    }
    if ($data['ca_rostered'] !== ($model['ca_rostered'] ?? null) && $data['ca_rostered'] !== null && ($data['ca_roster_checked_on'] ?? '') === ($model['ca_roster_checked_on'] ?? '')) {
        $data['ca_roster_checked_on'] = date('Y-m-d');
    }
    if (isset($_POST['caliber_confirmed']) && $data['data_notes'] !== null) {
        $data['data_notes'] = trim(str_replace(trim(PLACEHOLDER_NOTE), '', $data['data_notes'])) ?: null;
    }
    if (!$data['slug']) {
        $data['slug'] = trim(preg_replace('/[^a-z0-9]+/', '-', strtolower($data['manufacturer'] . ' ' . $data['model'])), '-');
    }
    try {
        if (!$data['manufacturer'] || !$data['model']) {
            throw new RuntimeException('Manufacturer and model are required.');
        }
        // No repeats: the same make + model (ignoring spaces, case and punctuation) may exist only once.
        foreach ($db->query('SELECT id, manufacturer, model FROM firearms') as $r) {
            if ((int)$r['id'] !== $id && $norm($r['manufacturer']) === $norm($data['manufacturer']) && $norm($r['model']) === $norm($data['model'])) {
                if (!$id && $returnListing) {
                    flash($r['manufacturer'] . ' ' . $r['model'] . ' was already in Firearms, so it has been selected.');
                    redirect($backToListing((int)$r['id']));
                }
                throw new RuntimeException($r['manufacturer'] . ' ' . $r['model'] . ' is already in Firearms (#' . $r['id'] . '). Use that one instead of adding it again.');
            }
        }
        if ($id) {
            $set = implode(', ', array_map(fn($k) => "$k = :$k", array_keys($data)));
            $db->prepare("UPDATE firearms SET $set, updated_at = datetime('now') WHERE id = :id")->execute($data + ['id' => $id]);
            stock_rename((string)$model['slug'], (string)$data['slug']);   // the stock photo is named after the slug
            flash('Firearm saved.');
        } else {
            $cols = implode(', ', array_keys($data));
            $db->prepare("INSERT INTO firearms ($cols) VALUES (:" . implode(', :', array_keys($data)) . ')')->execute($data);
            $id = (int)$db->lastInsertId();
            flash($returnListing ? 'Firearm added. Now fill in the details of this gun.' : 'Firearm added.');
        }
        redirect($returnListing ? $backToListing($id) : url('admin/model.php', ['id' => $id]));
    } catch (Throwable $e) {
        flash(friendly_db_error($e), 'err');
        $model = array_merge($model ?? [], $data);
    }
}

$v = $model ?? ['category' => 'handgun'];
// Pre-fill from the search typed on the listing page: a known manufacturer at the start goes in Manufacturer.
$q = trim(get_str('q', ''));
if (!$model && $q !== '') {
    $v['model'] = $q;
    foreach ($db->query('SELECT DISTINCT manufacturer FROM firearms ORDER BY LENGTH(manufacturer) DESC')->fetchAll(PDO::FETCH_COLUMN) as $mf) {
        if (stripos($q . ' ', $mf . ' ') === 0) {
            $v['manufacturer'] = $mf;
            $v['model'] = trim(substr($q, strlen($mf)));
            break;
        }
    }
}
// Pre-fill from a CA roster entry ("Use this" below, or "Add as a new firearm" on the roster page).
$fromRoster = null;
if (!$model && isset($_GET['roster'])) {
    $st = $db->prepare('SELECT * FROM ca_roster WHERE detail_path = ? LIMIT 1');
    $st->execute([get_str('roster')]);
    if ($fromRoster = $st->fetch() ?: null) {
        $make = roster_display_make($db, $fromRoster['manufacturer']);
        $name = roster_clean_model($fromRoster['model_base']);
        if (roster_make_key($make) === 'glock' && preg_match('/^\d/', $name)) {
            $name = 'G' . $name;   // match the shop's naming, e.g. roster "19" -> "G19"
        }
        $v = array_merge($v, [
            'manufacturer' => $make, 'model' => $name, 'category' => 'handgun',
            'caliber' => canonical_value('caliber', $fromRoster['caliber']), 'barrel_length_in' => $fromRoster['barrel_length_in'],
            'frame_material' => $fromRoster['material'], 'action' => $fromRoster['gun_type'] === 'Revolver' ? 'Revolver' : null,
            'ca_rostered' => 1, 'ca_roster_checked_on' => date('Y-m-d'), 'ca_roster_entry' => $fromRoster['detail_path'],
            'source_url' => ROSTER_SITE . $fromRoster['detail_path'],
        ]);
    }
}
// Roster search on the new-firearm page (starts with the text typed on the listing page).
$rosterQ = trim(isset($_GET['roster_q']) ? get_str('roster_q') : ($fromRoster ? '' : $q));
$rosterInfo = roster_status($db);
$rosterResults = (!$model && !$fromRoster && $rosterQ !== '' && $rosterInfo['rows']) ? roster_search($db, $rosterQ, 15) : [];

$placeholder = strpos((string)($v['data_notes'] ?? ''), trim(PLACEHOLDER_NOTE)) !== false;
$heading = $model ? $v['manufacturer'] . ' ' . $v['model'] : 'New firearm';
$listings = [];
if ($id) {
    $ls = $db->prepare('SELECT id, stock_number, status FROM listings WHERE firearm_id = ? ORDER BY id');
    $ls->execute([$id]);
    $listings = $ls->fetchAll();
}

admin_header($heading, 'models');
?>
<div class="crumbs"><a href="<?= e(url('admin/models.php')) ?>">Firearms</a> / <?= e($heading) ?></div>
<div class="admin-head"><h1 class="page-title"><?= e($heading) ?></h1></div>
<?php if ($model): ?>
  <p class="muted">Changes here apply to every listing of this firearm (<?= count($listings) ?>).
    <a href="<?= e(url('admin/listing.php', ['firearm_id' => $id])) ?>">Add a listing for this firearm</a></p>

  <?php
  $stockNow = stock_photo_url($model['slug'] ?? null, true);
  $preview = $_SESSION['stock_preview'][$id] ?? null;
  $previewSrc = null;
  if ($preview && is_file($preview['file'])) {
      // Small inline preview of the downloaded photo (it isn't on the site until "Use this photo").
      $bytes = (string)file_get_contents($preview['file']);
      $info = @getimagesizefromstring($bytes);
      if ($info && $info[0] * $info[1] <= 16_000_000 && ($im = @imagecreatefromstring($bytes))) {
          $pw = min(480, $info[0]);
          $out = imagecreatetruecolor($pw, (int)round($info[1] * $pw / $info[0]));
          imagefill($out, 0, 0, imagecolorallocate($out, 255, 255, 255));
          imagecopyresampled($out, $im, 0, 0, 0, 0, imagesx($out), imagesy($out), $info[0], $info[1]);
          ob_start();
          imagejpeg($out, null, 80);
          $previewSrc = 'data:image/jpeg;base64,' . base64_encode(ob_get_clean());
      }
  }
  $stockForm = fn(string $action, string $label, string $class = 'btn btn-outline btn-sm', string $extra = '') =>
      '<form method="post" action="' . e(url('admin/model.php', ['id' => $id])) . '" class="inline-form">' . csrf_field()
      . '<input type="hidden" name="stock_action" value="' . e($action) . '">' . $extra
      . '<button class="' . e($class) . '" type="submit">' . e($label) . '</button></form>';
  ?>
  <section class="stock-admin" id="stock-photo" aria-labelledby="stock-photo-title">
    <h2 id="stock-photo-title">Stock photo</h2>
    <p class="muted small">Shown on <strong>new</strong> listings of this firearm until they have photos of their own, labelled "Stock photo" with the note: <?= e(STOCK_PHOTO_NOTE) ?> Never shown on used guns.</p>
    <div class="stock-admin-row">
      <div class="stock-admin-img">
        <?php if ($stockNow): ?><img src="<?= e($stockNow) ?>" alt="Current stock photo"><?php else: ?><span class="muted">No stock photo yet</span><?php endif; ?>
      </div>
      <div class="stock-admin-actions">
        <?php if ($previewSrc): ?>
          <div class="stock-preview">
            <strong>Found on the manufacturer page:</strong>
            <img src="<?= $previewSrc ?>" alt="Photo found on the manufacturer page">
            <span class="muted small"><?= e($preview['image']) ?></span>
            <div class="stock-preview-btns">
              <?= $stockForm('use', 'Use this photo', 'btn btn-accent btn-sm') ?>
              <?= $stockForm('discard', 'Discard', 'link-btn') ?>
            </div>
          </div>
        <?php endif; ?>
        <form method="post" action="<?= e(url('admin/model.php', ['id' => $id])) ?>" class="stock-find">
          <?= csrf_field() ?>
          <input type="hidden" name="stock_action" value="find">
          <label for="stock_page">Manufacturer page</label>
          <div class="stock-find-row">
            <input class="input" id="stock_page" name="stock_page" type="url" value="<?= e(stock_page_for($model) ?? '') ?>" placeholder="https://manufacturer.com/product-page">
            <button class="btn btn-dark btn-sm" type="submit">Find photo</button>
          </div>
        </form>
        <form method="post" action="<?= e(url('admin/model.php', ['id' => $id])) ?>" enctype="multipart/form-data" class="stock-upload">
          <?= csrf_field() ?>
          <input type="hidden" name="stock_action" value="upload">
          <label for="stock_file">Or upload one</label>
          <div class="stock-find-row">
            <input id="stock_file" name="stock_file" type="file" accept="image/jpeg,image/png,image/webp" required>
            <button class="btn btn-outline btn-sm" type="submit">Upload</button>
          </div>
        </form>
        <?php if ($stockNow): ?><?= $stockForm('remove', 'Remove stock photo', 'link-btn') ?><?php endif; ?>
      </div>
    </div>
  </section>
<?php endif; ?>

<?php if ($returnListing): ?>
  <div class="alert alert-ok" role="status">Add the firearm, then you'll go straight back to the listing with it selected. Only Manufacturer, Model and Type are required; specs can be added later.</div>
<?php endif; ?>

<?php if (!$model && $rosterInfo['rows']): ?>
<section class="roster-pick">
  <?php if ($fromRoster): ?>
    <p style="margin:0"><strong>Filled in from the CA roster:</strong> <?= e($fromRoster['manufacturer'] . ' ' . $fromRoster['model']) ?> (<?= e($fromRoster['caliber']) ?>).
      Check the model name, then add the firearm. <a href="<?= e(url('admin/model.php', ['return' => $returnListing ? 'listing' : null, 'listing' => $returnId ?: null])) ?>">Start over</a></p>
  <?php else: ?>
    <h2 style="margin:0;font-size:20px">Handgun? Start from the CA roster</h2>
    <form method="get" action="<?= e(url('admin/model.php')) ?>" class="admin-filters">
      <?php if ($returnListing): ?><input type="hidden" name="return" value="listing"><?php endif; ?>
      <?php if ($returnId): ?><input type="hidden" name="listing" value="<?= $returnId ?>"><?php endif; ?>
      <label for="roster_q" class="sr-only">Search the CA roster</label>
      <input class="input" id="roster_q" name="roster_q" type="search" value="<?= e($rosterQ) ?>" placeholder="e.g. glock 19, smith 686, ruger lcr">
      <button class="btn btn-dark" type="submit">Search roster</button>
    </form>
    <?php if ($rosterQ !== '' && !$rosterResults): ?>
      <p class="muted small" style="margin:0">Nothing on the roster matches "<?= e($rosterQ) ?>". Off-roster, older or long guns: fill in the form below.</p>
    <?php endif; ?>
    <?php if ($rosterResults): ?>
      <ul class="cands">
      <?php foreach ($rosterResults as $r): ?>
        <li><a class="btn btn-outline btn-sm" href="<?= e(url('admin/model.php', ['roster' => $r['detail_path'], 'return' => $returnListing ? 'listing' : null, 'listing' => $returnId ?: null])) ?>">Use this</a>
          <?= e($r['manufacturer'] . ' ' . $r['model']) ?> <span class="muted">— <?= e($r['caliber']) ?><?= $r['barrel_length_in'] !== null ? ', ' . e(num($r['barrel_length_in'])) . '" barrel' : '' ?>, <?= e($r['gun_type']) ?></span></li>
      <?php endforeach; ?>
      </ul>
    <?php endif; ?>
    <p class="muted small" style="margin:0">Picking a roster entry fills in make, model, caliber, barrel length, frame and CA roster status.</p>
  <?php endif; ?>
</section>
<?php endif; ?>
<form method="post" action="<?= e(url('admin/model.php', ['id' => $id ?: null, 'return' => $returnListing ? 'listing' : null, 'listing' => $returnId ?: null])) ?>" class="admin-form">
  <?= csrf_field() ?>
  <?php foreach ($groups as $legend => $fields): ?>
    <fieldset>
      <legend><?= e($legend) ?></legend>
      <div class="grid-2">
      <?php foreach ($fields as [$col, $label, $type, $hint]):
          $value = $v[$col] ?? null;
          $wide = in_array($type, ['textarea'], true) || in_array($col, ['description', 'product_url', 'source_url', 'data_notes'], true); ?>
        <div class="field<?= $wide ? ' span-2' : '' ?>">
          <label for="<?= $col ?>"><?= e($label) ?></label>
          <?php if ($type === 'textarea'): ?>
            <textarea class="input" id="<?= $col ?>" name="<?= $col ?>" rows="<?= $col === 'description' ? 5 : 3 ?>"><?= e($value ?? '') ?></textarea>
          <?php elseif ($type === 'category'): ?>
            <select class="select" id="<?= $col ?>" name="<?= $col ?>"><?php foreach (CATEGORIES as $c) echo opt($c, type_label($c) . ($c === 'other' ? ' (receivers, kits)' : ''), $value); ?></select>
          <?php elseif ($type === 'choice'):
              // Values already used in Firearms (with how many use each), plus "Add a new one".
              $known = $db->query("SELECT $col AS v, COUNT(*) AS n FROM firearms WHERE TRIM(COALESCE($col, '')) <> '' GROUP BY $col ORDER BY $col COLLATE NOCASE")->fetchAll();
              $inList = $value === null || $value === '' || in_array($value, array_column($known, 'v'), true); ?>
            <select class="select choice-select" id="<?= $col ?>" name="<?= $col ?>" data-choice="<?= e(strtolower($label)) ?>">
              <?= opt('', '— Not set —', $value ?? '') ?>
              <?php foreach ($known as $k) echo opt($k['v'], $k['v'] . ' (' . (int)$k['n'] . ')', $value ?? ''); ?>
              <?php if (!$inList): ?><?= opt($value, $value . ' (this firearm)', $value) ?><?php endif; ?>
              <option value="__new">Add a new one…</option>
            </select>
            <span class="choice-new">
              <label for="<?= $col ?>__new" class="sr-only">New <?= e(strtolower($label)) ?></label>
              <input class="input" id="<?= $col ?>__new" name="<?= $col ?>__new" type="text" placeholder="Type the new <?= e(strtolower($label)) ?>" autocomplete="off">
            </span>
          <?php elseif ($type === 'roster'): ?>
            <select class="select" id="<?= $col ?>" name="<?= $col ?>">
              <?= opt('', 'Not checked / not a handgun', $value ?? '') ?><?= opt('1', 'On the roster', $value ?? '') ?><?= opt('0', 'Not on the roster — LEO Sales Only when new', $value ?? '') ?>
            </select>
          <?php else: ?>
            <input class="input<?= $type === 'num' ? ' mono' : '' ?>" id="<?= $col ?>" name="<?= $col ?>" type="<?= $type === 'date' ? 'date' : 'text' ?>"<?= $type === 'num' ? ' inputmode="decimal"' : '' ?> value="<?= e($type === 'num' && $value !== null ? num($value, 4) : ($value ?? '')) ?>">
          <?php endif; ?>
          <?php if ($hint): ?><span class="hint"><?= e($hint) ?></span><?php endif; ?>
          <?php if ($col === 'caliber' && $placeholder): ?>
            <label class="check"><input type="checkbox" name="caliber_confirmed" value="1"> Caliber is now correct (clears the "placeholder" note)</label>
          <?php endif; ?>
        </div>
      <?php endforeach; ?>
      </div>
    </fieldset>
  <?php endforeach; ?>
  <div class="save-bar"><button class="btn btn-accent" type="submit"><?= $model ? 'Save firearm' : ($returnListing ? 'Add firearm and go back to the listing' : 'Add firearm') ?></button>
    <a class="link-btn" href="<?= e($returnListing ? url('admin/listing.php', ['id' => $returnId ?: null]) : url('admin/models.php')) ?>">Cancel</a></div>
</form>
<?php admin_footer();
